// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUCMinas.SGQ.Processos.Data.Context;

namespace PUCMinas.SGQ.Processos.Data.Migrations
{
    [DbContext(typeof(ProcessosDbContext))]
    partial class ProcessosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<DateTime?>("DataCriacao");

                    b.Property<DateTime?>("DataUltimaAtualizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IncidenteCadastrado");

                    b.Property<Guid>("OperadorId");

                    b.Property<Guid>("PassoId");

                    b.HasKey("Id");

                    b.HasIndex("PassoId")
                        .IsUnique();

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.Passo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataCriacao");

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime?>("DataInicio");

                    b.Property<DateTime?>("DataUltimaAtualizacao");

                    b.Property<bool>("Finalizado");

                    b.Property<bool>("Iniciado");

                    b.Property<Guid>("OperadorId");

                    b.Property<Guid>("WorflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorflowId");

                    b.ToTable("Passos");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.PassoDefinicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataCriacao");

                    b.Property<DateTime?>("DataUltimaAtualizacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Ordem");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("WorkflowDefinicaoId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinicaoId");

                    b.ToTable("PassosDefinicao");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataCriacao");

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime?>("DataInicio");

                    b.Property<DateTime?>("DataUltimaAtualizacao");

                    b.Property<bool>("Finalizado");

                    b.Property<bool>("Iniciado");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.WorkflowDefinicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataCriacao");

                    b.Property<DateTime?>("DataUltimaAtualizacao");

                    b.Property<Guid>("EngenherioCriadorId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowsDefinicao");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.Parada", b =>
                {
                    b.HasOne("PUCMinas.SGQ.Processos.Business.Models.Passo", "Passo")
                        .WithOne("Parada")
                        .HasForeignKey("PUCMinas.SGQ.Processos.Business.Models.Parada", "PassoId");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.Passo", b =>
                {
                    b.HasOne("PUCMinas.SGQ.Processos.Business.Models.Workflow", "Workflow")
                        .WithMany("Passos")
                        .HasForeignKey("WorflowId");
                });

            modelBuilder.Entity("PUCMinas.SGQ.Processos.Business.Models.PassoDefinicao", b =>
                {
                    b.HasOne("PUCMinas.SGQ.Processos.Business.Models.WorkflowDefinicao", "WorkflowDefinicao")
                        .WithMany("PassosDefinicao")
                        .HasForeignKey("WorkflowDefinicaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
